language: python
python:
  - "3.6"

services:
  docker

before_script:
  install:
    - pip install pip-install docker-compose
  script:
    - docker-compose run app sh -c "python manage.py test && flake8"